apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-cert
  namespace: default
spec:
  dnsNames:
  - test.itops.frontline.rocks
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: task-issuer 
  secretName: app-cert-secret
  usages:
  - digital signature
  - key encipherment
