apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: app-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: app-issuer-account-key
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
