controller:
  extraArgs:
    http-port: 8080
    https-port: 8081

  containerPort:
    http: 8080
    https: 8081

  image:
    allowPrivilegeEscalation: false

  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
